[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]
aptPkgs = ["git", "python3", "build-essential", "gcc", "g++", "make"]
env = ["NODE_VERSION=20.18.0"]

[phases.install]
cmds = ["yarn install"]

[start]
cmd = "yarn start"
